### ISSUE TITLE
enable deployment to another hostname

### ISSUE THREAD

**Issue by martinjrobins** [Battery-Intelligence-Lab/galvanalyser#67]
Should be able to specify a hostname in '.env' for the deployment, this should affect:

1. allowed hostnames in django 'settings.py'
2. allowed cors and csrf hostnames in 'settings.py'
3. api url in frontend 'Api.js' (and 'APIConnection')

**Comment by martinjrobins** [comment]
btw. I'm still getting some CORS errors, even when I adjust all the hostnames manually as above:

'''
Access to fetch at 'http://51.104.20.4:5000/login/' from origin 'http://51.104.20.4' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
'''

**Comment by mjaquiery** [comment]
We should definitely be able to do this. I'm guessing we are missing a trick somewhere; I'll hopefully have my memory jogged when I start investigating!

**Comment by mjaquiery** [comment]
@martinjrobins how are we testing this -- if it's the Azure deployment I'll look into it when I've got access, but if you can think of a quick local method of testing I'll look into it without waiting.

**Comment by mjaquiery** [comment]
Okay, this is due to the CORS rules expecting the server to run on port 3000, while in the production docker-compose setup it runs on port 80. This probably deserves a good long-term fix where we properly figure out how to separate dev and production environments. 
In the meantime, I've allowed specifying the CORS_ALLOWED_ORIGINS in the .env file, but ultimately this is going to be pretty finickity. A more robust overall solution will be to figure out whether we want the SSL/etc. stuff to be part of the project (in which case modifying our existing `./frontend/nginx.conf` file would be sensible, or whether the project as a whole should sit unsecured and we leave it to deployment concerns to provide a proxy server to handle incoming traffic and provide SSL etc. Either way, the internal communication between frontend and backend can be done with http rather than https.

**Comment by martinjrobins** [comment]
I don't think this is the issue, I'm pretty sure I updated CORS_ALLOWED_ORIGINS with the right hostname on the azure vm. I'm guessing you'll see the issue when your browser is not on the same machine as the server. Do you have another machine you can install galvanalyser on? Then try to access it remotely from a separate machine.

**Comment by martinjrobins** [comment]
> but if you can think of a quick local method of testing I'll look into it without waiting.

Just need to install galvanalyser on a separate machine and point your browser at it, anythink other than `localhost` should show the error
