### ISSUE TITLE
validation of inputs (checking strings, numbers etc. with an appropriate error message appearing)

### ISSUE THREAD

**Issue by martinjrobins** [Battery-Intelligence-Lab/galvanalyser#9]
The forms in the frontend do not have appropriate input validation and display of errors from the rest api

**Comment by mjaquiery** [comment]
This is still very much true and should be fixed in version 2. 

There's a template of how this can be implemented using Snackbar (aka Toast) elements in the `UserProfile.tsx` part of the frontend, although currently the frontend API interface doesn't usefully expose errors, so that would need reworking a bit to allow those errors to flow through and be caught.

**Comment by mjaquiery** [comment]
Initial work on this now pushed to v2.0.0 branch: (uninformative) errors from the `Connection._fetch` mechanism now feed back to the Core display and are shown as snackbar items.
Making the REST API return better errors will now help with this; adding backend label.

**Comment by mjaquiery** [comment]
This should be sufficiently resolved for now by recent changes to expose the responses from the REST API, along with the backend work which described and validated inputs correctly and improved the descriptiveness of error messages.
